### PR TITLE
Add support for bundles with shared chunks

### PR DESCRIPTION
**Pull request by dmytrokyrychuk**
Works with webpack configs such as this:

```js
module.exports = {
  ...
  optimization: {
    splitChunks: {
      chunks: 'all',
    },
  },
};
```

When rendering a bundle with `{% render_bundle 'main' %}`, all chunks that `main` entry depends on will be included.

### CODE REVIEW

**Comment by hiimdoublej** [comment]
This branch works, kudos to @dmytrokyrychuk, thank you!

**Comment by mlazowik** [comment]
This is not enough, for chunks that are present in a lot of entry points the chunk name is truncated.

**Comment by bhrutledge** [comment]
@dmytrokyrychuk Are you able to close this PR? That would help folks who are learning about this issue to focus on #182.

**Comment by dmytrokyrychuk** [comment]
Oh, sorry. I thought I closed this PR earlier.

**Pull request closed without merging**
