### PR TITLE
Fix setup to include contrib module

### PR DESCRIPTION
**Pull request by destos**

### CODE REVIEW

**Comment by owais** [comment]
@destos can we please make sure the build passes all tests before merging the PR?

**Comment by owais** [comment]
Looks like an issue with Travis. Should be fixed in a few hours.

**Comment by destos** [comment]
@owais It looks like this fix hasn't been pushed to pypi yet? I've been using a git url for my requirements for a while and was wondering if It could be pushed up?

**Comment by owais** [comment]
@destos  Just published a newer version to pypi.

**Pull request merged**
