### PR TITLE
Let MANIFEST be created from MANIFEST.in automatically.

### PR DESCRIPTION
**Pull request by fladi**
There is no need to hardcode the MANIFEST file as distutils/setuptools will
automatically create it from a MANIFEST.in template.

This also adds README.md to the shipped files as it is currently missing in the
tarball present on PyPI.

### CODE REVIEW

**Comment by fladi** [comment]
@luzfcb That's not really necessary. Those `graft` and `global-exclude` commands would only make sense if there was a greedy `recursive-include dir *` in there (e.g. for a `docs/` folder structure).

**Comment by luzfcb** [comment]
this was the standard that has been used in own django
https://github.com/django/django/blob/master/MANIFEST.in
introduced in https://github.com/django/django/commit/93fc23b2d542105f5d129dff2dd2c8895e9abd5d

I suppose if I do not include `graft webpack_loader`, the `webpack_loader` folder should not be included in the generated package ( not tested, I need to confirm this )

said that, as you are modifying the generation of the package, It would be good to include `zip_safe=False,` in `setup.py`, to force not install the package as an compressed .egg file, because django does not work well with packages in compressed .egg format

**Comment by fladi** [comment]
@luzfcb `graft webpack_loader` is not necessary, because that's the responsibility of setuptools when using the `MANIFEST.in` template to create the final `MANIFEST` file. All the packages listed by `setup.py` in `packages = [...]` are inserted in the final file. So there is no need for `graft`, it happens [automatically](https://docs.python.org/3/distutils/sourcedist.html#principle).

`zip_safe=False` [mandatory](https://pythonhosted.org/setuptools/setuptools.html#setting-the-zip-safe-flag) if your package tries to use any datafiles shipped with it during runtime. This is not the case for *django-webpack-loader*.

If you want a quick way to verify that my changes are correct, merge my branch and run `python setup.py sdist; tar tfz dist/*.tar.gz` to see the content of the source tarball that would be uploaded to PyPI.

**Comment by owais** [comment]
Looks good.  Could you please rebase on latest master so we remove conflicts and we'll go ahead and merge this.

**Comment by fladi** [comment]
@owais thanks, rebased my branch as requested.

**Comment by owais** [comment]
Thank you

**Pull request merged**
