### PR TITLE
Add support for storing stats file in staticstorage

### PR DESCRIPTION
**Pull request by shezadkhan137**
This is a small feature which allows the stats file to be able to be stored in the staticstorage. This is useful for when your static storage is non local (we use S3 with the django storages lib) it allows multiple webservers to access the same stats file.

### CODE REVIEW

**Comment by owais** [comment]
@shezadkhan137 Most people (including me), check in the stats file to source control system or add it to your final build before deploying along with new python code.

**Comment by owais** [comment]
Closing for now. Please re-open if the above solution doesn't work for you.

**Comment by jpulec** [comment]
Is there a way you'd consider some sort of proposal for storing the stats file in staticfiles? 

Currently, I don't check my stats file into source control. We're working towards continuous deployment, so manually adding and committing my stats file isn't really an option.

Additionally, we're deployed on heroku, and since it is ephemeral we can't just generate a stats file in a post deploy script. This pretty much leaves staticfiles as our best option.

**Comment by ryanhiebert** [comment]
I also run on Heroku, and I'll share my setup. I use both the `heroku/nodejs` buildpack and the `heroku/python` buildpack, in that order. `webpack-bundle-tracker` is installed and configured for production, so when Heroku runs `npm install` in the buildpack my `postinstall` script in `package.json` runs `webpack -p --config webpack.prod.config.js`, which generates the stats file, which is in turn included in the slug.

I hope that clarifies things. I agree with others that, at least for Heroku, keeping it outside static files makes a lot of sense. It's certainly what I prefer.

**Comment by jpulec** [comment]
@ryanhiebert Ah. A postinstall script that runs in the same dyno. Excellent. Thanks for the awesome idea!

**Comment by ryanhiebert** [comment]
No problem. You'll find it absolutely critical for building bundles as late as possible (don't include build artifacts in the repository), which enables neat stuff like using babel-loader for using ES6. Lots of good stuff.

**Pull request closed without merging**
