### PR TITLE
checkout output

### PR DESCRIPTION
**Pull request by stevepeak**
Please do not merge yet, just testing

### CODE REVIEW

**Comment by stevepeak** [comment]
@owais this is strange. It's working, but not sure why not on your master branch...

**Comment by owais** [comment]
May be `coverage xml` before calling `codecov` does the trick? I tried locally and it generates a coverage.xml which is not present otherwise.

**Comment by stevepeak** [comment]
Well Codecov itself should call that command, which it does for my projects. Via https://github.com/codecov/codecov-python/blob/b3cc476866392ff38aeace4b8105315eeec93195/codecov/__init__.py#L72-L76

Not sure why this repo is having issues yet...

**Comment by owais** [comment]
@stevepeak  Would `root = os.getcwd()` return the directory that travis.yml is run from which is root of the repo, but codecov command is run from ./tests/. 

```python
try_to_run('coverage xml')
if os.path.exists(os.path.join(root, 'coverage.xml')):
```

First line creates `coverage.xml` in `./tests/` directory but second line looks for `./coverage.xml` at `./tests/coverage.xml`.

I'm not entirely sure this is it but worth a look.

**Comment by stevepeak** [comment]
That must be the issue...I'll make adjustments and keep trying. Lets keep this PR open so I can keep working on it.

Meanwhile, I'm using our global uploader which seems to work via `bash <(curl -s https://codecov.io/bash)`.

Thanks!

**Comment by owais** [comment]
@stevepeak I got it to work by doing this for now. https://github.com/owais/django-webpack-loader/blob/master/.travis.yml#L11-L14 

You can close this PR if you don't need it anymore. Feel free to keep it for testing purpose though.

**Pull request closed without merging**
